name: Otelcol Lightstep Receiver build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-receiver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
          cahce: false

      - name: Test
        run: make check

      - name: Build
        run: make build

      - name: Release new version
        env:
          GH_TOKEN: ${{ github.token }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |-
          git gh-tag $GIT_TAG
          git gh-release -m "Otelcol Lightstep Receiver Alpha ($GIT_TAG)" $GIT_TAG


      - name: Publish new version
        env:
          GH_TOKEN: ${{ github.token }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        run: |-
          sleep 60 && make --file=config/Makefile.base --trace version-publish || true
          
